[package]
name = "notificator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.21.0"
notify-rust = "4"
log = "0.4.21"
env_logger = "0.11.3"
url = "2.5.0"
ctrlc = "3.4"